export const CustomHttpSuccess = {
  SIGNUP_SUCCESS: '회원가입 성공',
  SIGNIN_SUCCESS: '로그인 성공',
  GET_MY_INFO_SUCCESS: '내 정보 보기 성공',
  ADD_CATEGORY_SUCCESS: '카테고리 추가 성공',
  GET_CATEGORIES_SUCCESS: '카테고리 리스트 성공',
  UPDATE_CATEGORY_SUCCESS: '카테고리 수정 성공',
  DELETE_CATEGORY_SUCCESS: '카테고리 삭제 성공',
  ADD_TODO_SUCCESS: 'ToDo 추가 성공',
  GET_TODOS_SUCCESS: 'ToDo 리스트 성공',
  UPDATE_TODO_SUCCESS: 'ToDo 수정 성공',
  DELETE_TODO_SUCCESS: 'ToDo 삭제 성공',
  ADD_TEMPLATE_SUCCESS: '템플릿 추가 성공',
  GET_TEMPLATES_SUCCESS: '템플릿 리스트 성공',
  UPDATE_TEMPLATE_SUCCESS: '템플릿 수정 성공',
  DELETE_TEMPLATE_SUCCESS: '템플릿 삭제 성공',
  ADD_CATEGORY_TO_TEMPLATE_SUCCESS: '템플릿에 카테고리 추가 성공',
  GET_TEMPLATE_CATEGORIES_SUCCESS: '모든 템플릿 카테고리 리스트 성공',
  REMOVE_CATEGORY_FROM_TEMPLATE_SUCCESS: '템플릿에서 카테고리 제거 성공',
  COPY_TEMPLATE_SUCCESS: '템플릿 복사 성공',
};
